name: couple_app
description: Couple app (Android + Web) - Option A smart polling
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  web: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
